apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tlag51idm-nodejs 
  janus-idp.io/tekton: tlag51idm-nodejs
  backstage.io/kubernetes-id: tlag51idm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tlag51idm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  